<?php

/**
 * @file
 * Primary module hooks for welcome module.
 *
 */

/**
 * Implements hook_theme().
 */
function welcome_theme($existing, $type, $theme, $path) {
  return [
    'welcome_template' => [
      'variables' => [
        'user_id' => [],
        'user_name' => [],
        'message' => [],
        'login_date' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_welcome_template().
 */

function welcome_preprocess_welcome_template(&$variables) {
  $config = \Drupal::config('welcome.settings');
  $user = \Drupal::currentUser();
  
  $user_id = $user->id();
  $user_name = $user->getDisplayName();
  $login_date = $user->getLastAccessedTime();
  $welcome_message = $config->get('message');

  $variables['user_id'] = $user_id;
  $variables['user_name'] = $user_name;
  $variables['message'] = $welcome_message;
  $variables['login_date'] = $login_date;
}